spring:
 application:
   name: access-properties
 cloud:
   config:
     enabled: false
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
 datasource:
   url: jdbc:mysql://localhost:3306/property-access
   username: root
   password: rahmin4101